name: MVNP-Autohome
main: com.jellyrekt.mvnpautohome.MVNPAutohome
version: 1.0-SNAPSHOT
author: JellyRekt
api-version: 1.13
depend: ['Multiverse-NetherPortals', 'Essentials']
commands:
  mvnph:
    description: Generic Multiverse-NetherPortals command
    usage: /<command>